services:
  apache:
    build: ./apache
    container_name: apache_confusion
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./php:/var/www/html
      - ./apache/.htpasswd:/usr/local/apache2/.htpasswd
      - ./static:/var/www/static

  php:
    image: php:8.2-fpm
    container_name: php_fpm
    volumes:
      - ./php:/var/www/html
      - ./static:/var/www/static